name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (örn: v1.0.0)'
        required: true
        default: 'v1.0.0'
      create_release:
        description: 'Release oluşturulsun mu?'
        type: boolean
        default: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_name: time_trapp_linux
          - os: windows-latest
            platform: windows
            artifact_name: time_trapp_windows
          - os: macos-latest
            platform: macos
            artifact_name: time_trapp_macos

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          cmake \
          ninja-build \
          pkg-config \
          libgtk-3-dev \
          liblzma-dev \
          libstdc++-12-dev \
          libayatana-appindicator3-dev \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          libxcursor-dev \
          libxinerama-dev \
          libgl1-mesa-dev \
          libasound2-dev

    - name: Install dependencies
      run: flutter pub get

#    - name: Run tests
#      run: flutter test

    - name: Clean build
      run: flutter clean

    - name: Build Linux
      if: matrix.os == 'ubuntu-latest'
      run: flutter build linux --release

    - name: Build Windows
      if: matrix.os == 'windows-latest'
      run: flutter build windows --release

    - name: Build macOS
      if: matrix.os == 'macos-latest'
      run: flutter build macos --release

    - name: Create release archive (Linux)
      if: matrix.platform == 'linux'
      run: |
        cd build/linux/x64/release/bundle
        tar -czf ../../../../${{ matrix.artifact_name }}.tar.gz .
        cd ../../../../../
        echo "Created ${{ matrix.artifact_name }}.tar.gz"
        ls -la ${{ matrix.artifact_name }}.tar.gz

    - name: Create release archive (Windows)
      if: matrix.platform == 'windows'
      shell: powershell
      run: |
        $sourcePath = "build/windows/x64/runner/Release"
        $zipPath = "${{ matrix.artifact_name }}.zip"
        Compress-Archive -Path "$sourcePath/*" -DestinationPath $zipPath -Force
        Write-Host "Created $zipPath"
        Get-ChildItem $zipPath

    - name: Create release archive (macOS)
      if: matrix.platform == 'macos'
      run: |
        cd build/macos/Build/Products/Release
        zip -r ../../../../../${{ matrix.artifact_name }}.zip Time\ Trapp.app
        cd ../../../../../
        echo "Created ${{ matrix.artifact_name }}.zip"
        ls -la ${{ matrix.artifact_name }}.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_version || github.ref_name }}
        name: Time Trapp ${{ github.event.inputs.release_version || github.ref_name }}
        body: |
          # Time Trapp ${{ github.event.inputs.release_version || github.ref_name }}
          
          ## 🎉 Release Notes
          
          Modern, cross-platform time tracking application for desktop.
          
          ### ✨ Features
          - One-click session start/stop
          - Real-time tracking with live counter
          - Detailed session management (purpose, goals, links)
          - Daily & hourly analytics
          - Advanced webhook integration with automatic username detection
          - Cross-platform support (macOS, Windows, Linux)
          - Modern Material Design UI
          - System tray integration
          
          ### 📱 Supported Platforms
          - macOS (Intel & Apple Silicon)
          - Windows (x64)
          - Linux (x64)
          
          ### 🔧 Installation
          1. Download the appropriate build for your platform
          2. Extract and run the application
          3. Follow the onboarding process
          4. Start tracking your time!
          
          ### 🚀 What's New
          - Automatic system username detection for webhooks
          - Cross-platform username support (Windows, macOS, Linux)
          - Smart username management with fallback options
          - Enhanced webhook reliability and error handling
          - Improved UI performance and state management
          - Comprehensive session filtering and reporting
          
          **Thank you for choosing Time Trapp!** 🎯
        files: |
          time_trapp_linux.tar.gz
          time_trapp_windows.zip
          time_trapp_macos.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
